[server]
port = 8501
headless = true
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
base = "light"

[logger]
level = "info"
